### PR TITLE
Dashboard skeleton

### PR DESCRIPTION
**Pull request by torbenal**
Looks like @KasperGroesLudvigsen and I have done some double work. I guess these can be merged.

Closes https://github.com/Dansk-Data-Science-Community/danish-data-science-salary-survey/issues/2.

### CODE REVIEW

**Comment by torbenal** [comment]
@saattrupdan

**Review by saattrupdan — CHANGES_REQUESTED** [review]
@torbenal Can you rename `main.py` to something like `dashboard.py`? Since we'll be doing more than a dashboard, so calling it main is a bit misleading. Otherwise looks good 🙂

**Comment by torbenal** [comment]
@saattrupdan

**Review by saattrupdan — APPROVED** [review]
LGTM!

**Pull request merged**
